FEATURETOOL = opp_featuretool
FEATURES_H = src/simu5g/common/features.h
PKG_CONFIG ?= pkg-config
SPACE_VEINS_ROOT ?= ../../space_veins
VEINS_ROOT ?= $(SPACE_VEINS_ROOT)/lib/veins
VEINS_INET_ROOT ?= $(VEINS_ROOT)/subprojects/veins_inet

# Satellite mobility depends on PROJ. Prefer pkg-config, but fall back to the
# standard Homebrew prefix so command-line builds match the IDE configuration.
PROJ_CFLAGS := $(shell $(PKG_CONFIG) --cflags proj 2>/dev/null)
PROJ_LIBS := $(shell $(PKG_CONFIG) --libs proj 2>/dev/null)
ifeq ($(strip $(PROJ_CFLAGS)),)
  ifneq ($(wildcard /opt/homebrew/include/proj.h),)
    PROJ_CFLAGS := -I/opt/homebrew/include
  endif
endif
ifeq ($(strip $(PROJ_LIBS)),)
  ifneq ($(wildcard /opt/homebrew/lib/libproj.dylib),)
    PROJ_LIBS := -L/opt/homebrew/lib -lproj
  endif
endif

.PHONY: all clean cleanall makefiles checkenvir checkmakefiles dist neddoc tests

all: makefiles $(FEATURES_H)
	@cd src && $(MAKE)

tests: all
	@cd src && $(MAKE) && cd ../tests/fingerprint/ && ./fingerprints

clean: makefiles
	@cd src && $(MAKE) clean

cleanall: makefiles
	@cd src && $(MAKE) MODE=release clean
	@cd src && $(MAKE) MODE=debug clean
	@rm -f src/Makefile $(FEATURES_H)

# extract makemake options from .oppbuildspec
# add -I. and -f at appropriate places to exactly match the makefile generated by the IDE
# note that the makemake options in .oppbuildspec are generated by the IDE and all --meta:xxx options must be thrown out
MAKEMAKE_OPTIONS := $(shell sed -n 's/.*makemake-options\s*=\s*"\([^"]*\)".*/\1/p' .oppbuildspec | sed 's/--meta:export-include-path/-I./g' | sed 's/--deep/-f --deep/g' | sed 's/ --meta:[^ ]*//g')
# add also options derived from enabled features
MAKEMAKE_OPTIONS := $(MAKEMAKE_OPTIONS) $(shell $(FEATURETOOL) options -f -l) -KINET_PROJ=$(INET_ROOT) -KGEOLIB=../../geographiclib -DSPACE_VEINS_IMPORT -DVEINS_IMPORT -DVEINS_INET_IMPORT -DINET_IMPORT -I. -I$$\(INET_PROJ\)/src -I$$\(GEOLIB\)/src -I$(SPACE_VEINS_ROOT)/src -I$(VEINS_ROOT)/src -I$(VEINS_INET_ROOT)/src $(PROJ_CFLAGS) -L$$\(INET_PROJ\)/src -L$$\(GEOLIB\)/BUILD/src -L$(SPACE_VEINS_ROOT)/src -L$(VEINS_ROOT)/src -L$(VEINS_INET_ROOT)/src -lINET$$\(D\) -lGeographicLib -lspace_veins$$\(D\) -lveins$$\(D\) -lveins_inet$$\(D\) $(PROJ_LIBS)

makefiles:
	@$(info *** CREATING Makefile with:)
	@$(info opp_makemake $(MAKEMAKE_OPTIONS))
	@cd src && opp_makemake $(MAKEMAKE_OPTIONS)

# generate an include file that contains all the WITH_FEATURE macros according to the current enablement of features
$(FEATURES_H): $(wildcard .oppfeaturestate) .oppfeatures
	@$(FEATURETOOL) defines >$(FEATURES_H).tmp
	@mv $(FEATURES_H).tmp $(FEATURES_H)

dist:
	releng/makedist

neddoc:
	@opp_neddoc --verbose --no-automatic-hyperlinks -x "/*/simulations,/*/tests,/*/showcases" .
