/*
 * WarningAlertPacket_types.h
 *
 *  Created on: May 24, 2021
 *      Author: linofex
 */

#ifndef APPS_MEC_WARNINGALERT_REST_PACKETS_WARNINGALERTPACKET_TYPES_H_
#define APPS_MEC_WARNINGALERT_REST_PACKETS_WARNINGALERTPACKET_TYPES_H_



#define START_WARNING "StartWarning"
#define STOP_WARNING "StoptWarning"

#define WARNING_ALERT "WarningAlert"

#endif /* APPS_MEC_WARNINGALERT_REST_PACKETS_WARNINGALERTPACKET_TYPES_H_ */
